name: Deploy Vue.js to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fronted # <— MUHIM: fronted papkasi
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: fronted/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build project
        # Agar Vite ishlatsa: npm run build dist'ga chiqaradi
        run: npm run build

      - name: Create SPA 404 and .nojekyll
        run: |
          cp -f dist/index.html dist/404.html
          touch dist/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'fronted/dist' # <— MUHIM: to‘liq yo‘l

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
