name: Deploy backend to VPS

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps & build
        run: |
          npm ci
          npm run build
          tar -czf backend.tar.gz dist package.json package-lock.json ecosystem.config.js

      - name: Upload tarball to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "backend/backend.tar.gz"
          target: "/home/${{ secrets.SSH_USER }}/"

      - name: Unpack, install, set env, reload pm2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            APP_DIR="${{ secrets.SERVER_DIR:-/var/www/backend }}"
            mkdir -p "$APP_DIR/releases/${GITHUB_SHA}"
            tar -xzf ~/backend.tar.gz -C "$APP_DIR/releases/${GITHUB_SHA}"
            rm ~/backend.tar.gz
            cd "$APP_DIR/releases/${GITHUB_SHA}"

            # env yozish
            printf "%s" "${{ secrets.ENV_FILE }}" > .env

            npm ci --omit=dev
            # symlink current -> release
            ln -sfn "$APP_DIR/releases/${GITHUB_SHA}" "$APP_DIR/current"
            cd "$APP_DIR/current"

            # pm2 start or reload
            pm2 startOrReload ecosystem.config.js --update-env
            pm2 save
